spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver